{% extends "layout.html" %}

{% block content %}    
    <main role="main" class="inner cover" id="main">
        <h1 class="cover-heading">HARNESS EVERY CLICK, TAP AND SWIPE.</h1>
        <p class="lead">Brand, track and optimize every touchpoint with Shortly, the world's leading link management platform.</p>
        <p
            class="lead d-flex align-items-center"
            v-if=" ! short"
        >
            <input
                type="text"
                v-model="link"
                class="form-control" 
                name="url"               
                placeholder="Paste a link to shorten it"
                :class="{'is-invalid': errors.first('url')}"
                v-validate="'required|url'"
                autofocus />
            <a 
                href="javascript:;" 
                class="btn btn-primary ml-2"
                v-on:click="onClickShorten"
                >shorten</a>
        </p>
        <p 
            v-else
            class="lead d-flex align-items-center"
        >
            <input 
                type="text"
                v-model="short"
                class="form-control"
                ref="copy"
                 />
            <button 
                v-on:click="onClickCopy"
                class="btn btn-primary ml-2"
                >
                <i class="fas fa-clone"></i>
            </button>
        </p>
    </main>
{% endblock %}

{% block scripts %}
    <script src="/js/main.js"></script>
{% endblock %}